version: '3.7'
services: 
  counter:
    image: artshoque/important-site:dev
    deploy:
      replicas: ${scaleNumber}
    volumes:
    - storage:/flask/logs
    labels:
    - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
    depends_on:
    - redis
    networks:
    - public
    - secret
  redis:
    image: redis:alpine
    volumes:
    - redis-data:/data
    networks:
    - secret
  loadbalancer:
    image: traefik:v1.7.19-alpine
    command: --docker
    labels:
    - "traefik.http.services.loadbalancer.loadbalancer.server.port=80"
    links:
    - counter
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 80:80
    networks:
    - public
volumes:
  redis-data:
    driver: local
  storage:
    driver: local
networks:
  secret:
    driver: bridge
  public:
    driver: bridge